/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function genSecretKey(): string
export function derivePubKey(secret: string): string
export function encryptFile(fileData: Uint8Array, pubStr: string): Uint8Array
export function decryptFile(encryptedData: Uint8Array, secretKeyStr: string): Uint8Array
